baseurl = "http://blog.food028.com"
title = "Yangzhiqiang Blog"
theme = "hugo-theme-cleanwhite-master"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "杨志强的博客 | Yangzhiqiang Blog"
  description = "杨志强，程序员, 开源爱好者，户外摄影爱好者 | 这里是 杨志强 的博客，与你一起发现更大的世界。"
  keyword = "杨志强, Yangzhiqiang , 杨志强的网络日志, 杨志强的博客, Yangzhiqiang Blog, 博客, 个人网站, 互联网, Web, 云原生, PaaS, Istio, Kubernetes, 微服务, Microservice"
  slogan = "路在脚下，心向远方"

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/avatar-yangzhiqiang.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2

  # Baidu Analytics
  ba_track_id = ""

  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true
  email          = "cqyangzhiqiang@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "full profile url in linkedin"
  stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "full profile url in github"
  wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"

  [[params.friend_link]]
  title = "food028"
  href =  "http://food028.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesh中文网"
  href =  "http://www.servicemesh.cn"
  [[params.bookmark_link]]
  title = "Awesome Service Mesh"
  href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  [[params.bookmark_link]]
  title =  "Image Compression"
  href = "https://tinypng.com"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
